/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  model?: string;
  slug?: Slug;
  series?: "analogue" | "digital" | "specialized";
  function?: "MFC" | "MFM";
  productLabel?: InternationalizedArrayString;
  features?: Array<{
    ko?: string;
    en?: string;
    zh?: string;
    _key: string;
  }>;
  connections?: Array<{
    type?: string;
    length?: string;
    _key: string;
  }>;
  massFlowSpecs?: {
    flowRange?: {
      display?: string;
      min?: number;
      max?: number;
      unit?: string;
      referenceGas?: string;
    };
    responseTime?: {
      display?: string;
      value?: number;
      unit?: string;
      comparator?: "lt" | "gt" | "eq";
    };
    accuracy?: {
      display?: string;
      value?: number;
      unit?: string;
    };
    repeatability?: {
      display?: string;
      value?: number;
      unit?: string;
    };
    ioSignal?: {
      display?: string;
      outputs?: Array<string>;
    };
    supplyPower?: {
      display?: string;
      voltages?: Array<number>;
      currentMA?: number;
    };
    maxPressure?: {
      display?: string;
      value?: number;
      unit?: string;
      comparator?: "lt" | "gt" | "eq";
    };
    tempRange?: {
      display?: string;
      min?: number;
      max?: number;
      unit?: string;
    };
    leakRate?: {
      display?: string;
      value?: number;
      unit?: string;
    };
    controlRange?: {
      display?: string;
      min?: number;
      max?: number;
      unit?: string;
    };
  };
  digitalCommunication?: {
    protocol?: string;
    baudRate?: number;
    dataBits?: number;
    stopBits?: number;
    parity?: "None" | "Even" | "Odd";
  };
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  dimensionDrawing?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type InternationalizedArrayStringValue = {
  _type: "internationalizedArrayStringValue";
  value?: string;
  language?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | InternationalizedArrayString
  | Slug
  | InternationalizedArrayStringValue
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries.ts
// Variable: productBySlugQuery
// Query: *[_type == "product" && slug.current == $slug][0]{      model,  slug,  series,  "function": function,  "productLabel": {    "ko": coalesce(productLabel[language == "ko"][0].value, productLabel[language == "en"][0].value),    "en": coalesce(productLabel[language == "en"][0].value, productLabel[language == "ko"][0].value),    "zh": coalesce(productLabel[language == "zh"][0].value, productLabel[language == "en"][0].value)  },  features,  connections,  massFlowSpecs,  digitalCommunication,  images,  dimensionDrawing  }
export type ProductBySlugQueryResult = {
  model: string | null;
  slug: Slug | null;
  series: "analogue" | "digital" | "specialized" | null;
  function: "MFC" | "MFM" | null;
  productLabel: {
    ko: string | null;
    en: string | null;
    zh: string | null;
  };
  features: Array<{
    ko?: string;
    en?: string;
    zh?: string;
    _key: string;
  }> | null;
  connections: Array<{
    type?: string;
    length?: string;
    _key: string;
  }> | null;
  massFlowSpecs: {
    flowRange?: {
      display?: string;
      min?: number;
      max?: number;
      unit?: string;
      referenceGas?: string;
    };
    responseTime?: {
      display?: string;
      value?: number;
      unit?: string;
      comparator?: "eq" | "gt" | "lt";
    };
    accuracy?: {
      display?: string;
      value?: number;
      unit?: string;
    };
    repeatability?: {
      display?: string;
      value?: number;
      unit?: string;
    };
    ioSignal?: {
      display?: string;
      outputs?: Array<string>;
    };
    supplyPower?: {
      display?: string;
      voltages?: Array<number>;
      currentMA?: number;
    };
    maxPressure?: {
      display?: string;
      value?: number;
      unit?: string;
      comparator?: "eq" | "gt" | "lt";
    };
    tempRange?: {
      display?: string;
      min?: number;
      max?: number;
      unit?: string;
    };
    leakRate?: {
      display?: string;
      value?: number;
      unit?: string;
    };
    controlRange?: {
      display?: string;
      min?: number;
      max?: number;
      unit?: string;
    };
  } | null;
  digitalCommunication: {
    protocol?: string;
    baudRate?: number;
    dataBits?: number;
    stopBits?: number;
    parity?: "Even" | "None" | "Odd";
  } | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  dimensionDrawing: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: productsBySeriesQuery
// Query: *[_type == "product" && series == $series] | order(function asc, model asc){      model,  slug,  series,  "function": function,  "productLabel": {    "ko": coalesce(productLabel[language == "ko"][0].value, productLabel[language == "en"][0].value),    "en": coalesce(productLabel[language == "en"][0].value, productLabel[language == "ko"][0].value),    "zh": coalesce(productLabel[language == "zh"][0].value, productLabel[language == "en"][0].value)  },  features,  connections,  massFlowSpecs,  digitalCommunication,  images,  dimensionDrawing  }
export type ProductsBySeriesQueryResult = Array<{
  model: string | null;
  slug: Slug | null;
  series: "analogue" | "digital" | "specialized" | null;
  function: "MFC" | "MFM" | null;
  productLabel: {
    ko: string | null;
    en: string | null;
    zh: string | null;
  };
  features: Array<{
    ko?: string;
    en?: string;
    zh?: string;
    _key: string;
  }> | null;
  connections: Array<{
    type?: string;
    length?: string;
    _key: string;
  }> | null;
  massFlowSpecs: {
    flowRange?: {
      display?: string;
      min?: number;
      max?: number;
      unit?: string;
      referenceGas?: string;
    };
    responseTime?: {
      display?: string;
      value?: number;
      unit?: string;
      comparator?: "eq" | "gt" | "lt";
    };
    accuracy?: {
      display?: string;
      value?: number;
      unit?: string;
    };
    repeatability?: {
      display?: string;
      value?: number;
      unit?: string;
    };
    ioSignal?: {
      display?: string;
      outputs?: Array<string>;
    };
    supplyPower?: {
      display?: string;
      voltages?: Array<number>;
      currentMA?: number;
    };
    maxPressure?: {
      display?: string;
      value?: number;
      unit?: string;
      comparator?: "eq" | "gt" | "lt";
    };
    tempRange?: {
      display?: string;
      min?: number;
      max?: number;
      unit?: string;
    };
    leakRate?: {
      display?: string;
      value?: number;
      unit?: string;
    };
    controlRange?: {
      display?: string;
      min?: number;
      max?: number;
      unit?: string;
    };
  } | null;
  digitalCommunication: {
    protocol?: string;
    baudRate?: number;
    dataBits?: number;
    stopBits?: number;
    parity?: "Even" | "None" | "Odd";
  } | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  dimensionDrawing: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: src/sanity/queries.ts
// Variable: productByModelQuery
// Query: *[_type == "product" && lower(model) == lower($model)][0]{      model,  slug,  series,  "function": function,  "productLabel": {    "ko": coalesce(productLabel[language == "ko"][0].value, productLabel[language == "en"][0].value),    "en": coalesce(productLabel[language == "en"][0].value, productLabel[language == "ko"][0].value),    "zh": coalesce(productLabel[language == "zh"][0].value, productLabel[language == "en"][0].value)  },  features,  connections,  massFlowSpecs,  digitalCommunication,  images,  dimensionDrawing  }
export type ProductByModelQueryResult = {
  model: string | null;
  slug: Slug | null;
  series: "analogue" | "digital" | "specialized" | null;
  function: "MFC" | "MFM" | null;
  productLabel: {
    ko: string | null;
    en: string | null;
    zh: string | null;
  };
  features: Array<{
    ko?: string;
    en?: string;
    zh?: string;
    _key: string;
  }> | null;
  connections: Array<{
    type?: string;
    length?: string;
    _key: string;
  }> | null;
  massFlowSpecs: {
    flowRange?: {
      display?: string;
      min?: number;
      max?: number;
      unit?: string;
      referenceGas?: string;
    };
    responseTime?: {
      display?: string;
      value?: number;
      unit?: string;
      comparator?: "eq" | "gt" | "lt";
    };
    accuracy?: {
      display?: string;
      value?: number;
      unit?: string;
    };
    repeatability?: {
      display?: string;
      value?: number;
      unit?: string;
    };
    ioSignal?: {
      display?: string;
      outputs?: Array<string>;
    };
    supplyPower?: {
      display?: string;
      voltages?: Array<number>;
      currentMA?: number;
    };
    maxPressure?: {
      display?: string;
      value?: number;
      unit?: string;
      comparator?: "eq" | "gt" | "lt";
    };
    tempRange?: {
      display?: string;
      min?: number;
      max?: number;
      unit?: string;
    };
    leakRate?: {
      display?: string;
      value?: number;
      unit?: string;
    };
    controlRange?: {
      display?: string;
      min?: number;
      max?: number;
      unit?: string;
    };
  } | null;
  digitalCommunication: {
    protocol?: string;
    baudRate?: number;
    dataBits?: number;
    stopBits?: number;
    parity?: "Even" | "None" | "Odd";
  } | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  dimensionDrawing: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: src/sanity/queries.ts
// Variable: allProductsQuery
// Query: *[_type == "product"]  | order(    select(series == "analogue" => 0, series == "digital" => 1, 2),    function asc,    model asc  ){      model,  slug,  series,  "function": function,  "productLabel": {    "ko": coalesce(productLabel[language == "ko"][0].value, productLabel[language == "en"][0].value),    "en": coalesce(productLabel[language == "en"][0].value, productLabel[language == "ko"][0].value),    "zh": coalesce(productLabel[language == "zh"][0].value, productLabel[language == "en"][0].value)  },  features,  connections,  massFlowSpecs,  digitalCommunication,  images,  dimensionDrawing  }
export type AllProductsQueryResult = Array<{
  model: string | null;
  slug: Slug | null;
  series: "analogue" | "digital" | "specialized" | null;
  function: "MFC" | "MFM" | null;
  productLabel: {
    ko: string | null;
    en: string | null;
    zh: string | null;
  };
  features: Array<{
    ko?: string;
    en?: string;
    zh?: string;
    _key: string;
  }> | null;
  connections: Array<{
    type?: string;
    length?: string;
    _key: string;
  }> | null;
  massFlowSpecs: {
    flowRange?: {
      display?: string;
      min?: number;
      max?: number;
      unit?: string;
      referenceGas?: string;
    };
    responseTime?: {
      display?: string;
      value?: number;
      unit?: string;
      comparator?: "eq" | "gt" | "lt";
    };
    accuracy?: {
      display?: string;
      value?: number;
      unit?: string;
    };
    repeatability?: {
      display?: string;
      value?: number;
      unit?: string;
    };
    ioSignal?: {
      display?: string;
      outputs?: Array<string>;
    };
    supplyPower?: {
      display?: string;
      voltages?: Array<number>;
      currentMA?: number;
    };
    maxPressure?: {
      display?: string;
      value?: number;
      unit?: string;
      comparator?: "eq" | "gt" | "lt";
    };
    tempRange?: {
      display?: string;
      min?: number;
      max?: number;
      unit?: string;
    };
    leakRate?: {
      display?: string;
      value?: number;
      unit?: string;
    };
    controlRange?: {
      display?: string;
      min?: number;
      max?: number;
      unit?: string;
    };
  } | null;
  digitalCommunication: {
    protocol?: string;
    baudRate?: number;
    dataBits?: number;
    stopBits?: number;
    parity?: "Even" | "None" | "Odd";
  } | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }> | null;
  dimensionDrawing: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "product" && slug.current == $slug][0]{\n    \n  model,\n  slug,\n  series,\n  "function": function,\n  "productLabel": {\n    "ko": coalesce(productLabel[language == "ko"][0].value, productLabel[language == "en"][0].value),\n    "en": coalesce(productLabel[language == "en"][0].value, productLabel[language == "ko"][0].value),\n    "zh": coalesce(productLabel[language == "zh"][0].value, productLabel[language == "en"][0].value)\n  },\n  features,\n  connections,\n  massFlowSpecs,\n  digitalCommunication,\n  images,\n  dimensionDrawing\n\n  }\n': ProductBySlugQueryResult;
    '\n  *[_type == "product" && series == $series] | order(function asc, model asc){\n    \n  model,\n  slug,\n  series,\n  "function": function,\n  "productLabel": {\n    "ko": coalesce(productLabel[language == "ko"][0].value, productLabel[language == "en"][0].value),\n    "en": coalesce(productLabel[language == "en"][0].value, productLabel[language == "ko"][0].value),\n    "zh": coalesce(productLabel[language == "zh"][0].value, productLabel[language == "en"][0].value)\n  },\n  features,\n  connections,\n  massFlowSpecs,\n  digitalCommunication,\n  images,\n  dimensionDrawing\n\n  }\n': ProductsBySeriesQueryResult;
    '\n  *[_type == "product" && lower(model) == lower($model)][0]{\n    \n  model,\n  slug,\n  series,\n  "function": function,\n  "productLabel": {\n    "ko": coalesce(productLabel[language == "ko"][0].value, productLabel[language == "en"][0].value),\n    "en": coalesce(productLabel[language == "en"][0].value, productLabel[language == "ko"][0].value),\n    "zh": coalesce(productLabel[language == "zh"][0].value, productLabel[language == "en"][0].value)\n  },\n  features,\n  connections,\n  massFlowSpecs,\n  digitalCommunication,\n  images,\n  dimensionDrawing\n\n  }\n': ProductByModelQueryResult;
    '\n  *[_type == "product"]\n  | order(\n    select(series == "analogue" => 0, series == "digital" => 1, 2),\n    function asc,\n    model asc\n  ){\n    \n  model,\n  slug,\n  series,\n  "function": function,\n  "productLabel": {\n    "ko": coalesce(productLabel[language == "ko"][0].value, productLabel[language == "en"][0].value),\n    "en": coalesce(productLabel[language == "en"][0].value, productLabel[language == "ko"][0].value),\n    "zh": coalesce(productLabel[language == "zh"][0].value, productLabel[language == "en"][0].value)\n  },\n  features,\n  connections,\n  massFlowSpecs,\n  digitalCommunication,\n  images,\n  dimensionDrawing\n\n  }\n': AllProductsQueryResult;
  }
}
