// AUTO-GENERATED FROM 2020 catalogue appendix (gas-conversion table).
// Source: docs/archive/2020-catalog/product-catalog-2020-en.md § 13.
// K-factors are physical constants; do not edit by hand.

export type GasCategory = "common" | "specialty";
export type GasSealNote = "kalrez" | "teflon" | "metal";

export type GasFactor = {
  /** kebab-case id, used in URL search params */
  id: string;
  /** typeset chemical formula, e.g. "N₂", "CO₂" */
  formula: string;
  /** K-factor relative to N₂ (= 1.000) */
  factor: number;
  /** English name (KO/ZH localization deferred to v1.1) */
  names: { en: string };
  /**
   * "common" = a standard elastomer (Viton/Buna/EPDM) is recommended for this gas;
   * "specialty" = needs Kalrez/Teflon/Metal seal — UI surfaces a verify-with-sales note.
   */
  category: GasCategory;
  /** Specific seal recommendation when category is "specialty". */
  sealNote?: GasSealNote;
  /** True for the seven gases pinned at the top of the picker. */
  pinned?: true;
  /**
   * Lowercased id + ASCII-folded formula + English name, joined for substring
   * search. Subscript digits are folded to ASCII so typing "CO2" matches "CO₂".
   */
  searchKey: string;
};

export const GAS_FACTORS: readonly GasFactor[] = [
  {
    id: "nitrogen",
    formula: "N₂",
    factor: 1,
    names: { en: "Nitrogen" },
    category: "common",
    pinned: true,
    searchKey: "nitrogen n2 nitrogen",
  },
  {
    id: "oxygen",
    formula: "O₂",
    factor: 0.988,
    names: { en: "Oxygen" },
    category: "common",
    pinned: true,
    searchKey: "oxygen o2 oxygen",
  },
  {
    id: "argon",
    formula: "Ar",
    factor: 1.395,
    names: { en: "Argon" },
    category: "common",
    pinned: true,
    searchKey: "argon ar argon",
  },
  {
    id: "helium",
    formula: "He",
    factor: 1.386,
    names: { en: "Helium" },
    category: "common",
    pinned: true,
    searchKey: "helium he helium",
  },
  {
    id: "hydrogen",
    formula: "H₂",
    factor: 1.008,
    names: { en: "Hydrogen" },
    category: "common",
    pinned: true,
    searchKey: "hydrogen h2 hydrogen",
  },
  {
    id: "air",
    formula: "Air",
    factor: 0.998,
    names: { en: "Air" },
    category: "common",
    pinned: true,
    searchKey: "air air air",
  },
  {
    id: "carbon-dioxide",
    formula: "CO₂",
    factor: 0.74,
    names: { en: "Carbon Dioxide" },
    category: "common",
    pinned: true,
    searchKey: "carbon-dioxide co2 carbon dioxide",
  },
  {
    id: "1-butene",
    formula: "C₄H₈",
    factor: 0.294,
    names: { en: "1-Butene" },
    category: "common",
    searchKey: "1-butene c4h8 1-butene",
  },
  {
    id: "1-pentene-4-methyl",
    formula: "C₆H₁₂",
    factor: 0.2,
    names: { en: "1-Pentene, 4-Methyl" },
    category: "specialty",
    searchKey: "1-pentene-4-methyl c6h12 1-pentene, 4-methyl",
  },
  {
    id: "1-1-difluoro-1-chloroethane",
    formula: "C₂H₃ClF₂",
    factor: 0.341,
    names: { en: "1,1-Difluoro-1-Chloroethane" },
    category: "common",
    searchKey:
      "1-1-difluoro-1-chloroethane c2h3clf2 1,1-difluoro-1-chloroethane",
  },
  {
    id: "1-1-difluoroethane",
    formula: "CH₃CHF₂",
    factor: 0.415,
    names: { en: "1,1-Difluoroethane" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "1-1-difluoroethane ch3chf2 1,1-difluoroethane",
  },
  {
    id: "1-1-difluoroethylene",
    formula: "CH₂:CF₂",
    factor: 0.458,
    names: { en: "1,1-Difluoroethylene" },
    category: "common",
    searchKey: "1-1-difluoroethylene ch2:cf2 1,1-difluoroethylene",
  },
  {
    id: "1-1-1-2-tetrafluoroethane-r134a",
    formula: "C₂H₂F₄",
    factor: 0.307,
    names: { en: "1,1,1,2-Tetrafluoroethane (R134A)" },
    category: "common",
    searchKey:
      "1-1-1-2-tetrafluoroethane-r134a c2h2f4 1,1,1,2-tetrafluoroethane (r134a)",
  },
  {
    id: "1-1-2-trichloro-1-1-2-trifluoroet-f113",
    formula: "C₂Cl₃F₃",
    factor: 0.231,
    names: { en: "1,1,2-Trichloro-1,1,2-Trifluoroet (f113)" },
    category: "common",
    searchKey:
      "1-1-2-trichloro-1-1-2-trifluoroet-f113 c2cl3f3 1,1,2-trichloro-1,1,2-trifluoroet (f113)",
  },
  {
    id: "1-1-2-2-tetrafluoroethane-r134",
    formula: "C₂H₂F₄",
    factor: 0.295,
    names: { en: "1,1,2,2-Tetrafluoroethane (R134)" },
    category: "specialty",
    searchKey:
      "1-1-2-2-tetrafluoroethane-r134 c2h2f4 1,1,2,2-tetrafluoroethane (r134)",
  },
  {
    id: "1-2-dibromotetrafluoroethane-f114b2",
    formula: "C₂Br₂F₄",
    factor: 0.215,
    names: { en: "1,2-Dibromotetrafluoroethane (f114B2)" },
    category: "specialty",
    sealNote: "teflon",
    searchKey:
      "1-2-dibromotetrafluoroethane-f114b2 c2br2f4 1,2-dibromotetrafluoroethane (f114b2)",
  },
  {
    id: "1-2-dichloroethane-ethylene-dichloride",
    formula: "C₂H₄Cl₂",
    factor: 0.382,
    names: { en: "1,2-Dichloroethane (Ethylene dichloride)" },
    category: "common",
    searchKey:
      "1-2-dichloroethane-ethylene-dichloride c2h4cl2 1,2-dichloroethane (ethylene dichloride)",
  },
  {
    id: "1-2-dichlorotetrafluoroethane-f114",
    formula: "C₂Cl₂F₄",
    factor: 0.231,
    names: { en: "1,2-Dichlorotetrafluoroethane (f114)" },
    category: "common",
    searchKey:
      "1-2-dichlorotetrafluoroethane-f114 c2cl2f4 1,2-dichlorotetrafluoroethane (f114)",
  },
  {
    id: "1-2-propylene-oxide",
    formula: "C₃H₆O",
    factor: 0.348,
    names: { en: "1,2-Propylene Oxide" },
    category: "specialty",
    searchKey: "1-2-propylene-oxide c3h6o 1,2-propylene oxide",
  },
  {
    id: "1-3-butadiene",
    formula: "C₄H₆",
    factor: 0.354,
    names: { en: "1,3-Butadiene" },
    category: "common",
    searchKey: "1-3-butadiene c4h6 1,3-butadiene",
  },
  {
    id: "2-chloro-1-1-1-2-tetrafluoroethane-r124",
    formula: "C₂HCIF₄",
    factor: 0.027,
    names: { en: "2-Chloro-1,1,1,2-Tetrafluoroethane (R124)" },
    category: "specialty",
    searchKey:
      "2-chloro-1-1-1-2-tetrafluoroethane-r124 c2hcif4 2-chloro-1,1,1,2-tetrafluoroethane (r124)",
  },
  {
    id: "2-chlorobutane",
    formula: "C₄H₉Cl",
    factor: 0.234,
    names: { en: "2-Chlorobutane" },
    category: "specialty",
    searchKey: "2-chlorobutane c4h9cl 2-chlorobutane",
  },
  {
    id: "2-methyl-1-3-butadiene",
    formula: "C₅H₈",
    factor: 0.247,
    names: { en: "2-Methyl-1,3-Butadiene" },
    category: "specialty",
    searchKey: "2-methyl-1-3-butadiene c5h8 2-methyl-1,3-butadiene",
  },
  {
    id: "2-2-dichloro-1-1-1-trifloroethane",
    formula: "C₂HCl₂F₃",
    factor: 0.259,
    names: { en: "2,2-Dichloro-1,1,1-Trifloroethane" },
    category: "specialty",
    searchKey:
      "2-2-dichloro-1-1-1-trifloroethane c2hcl2f3 2,2-dichloro-1,1,1-trifloroethane",
  },
  {
    id: "2-2-dimethylpropane",
    formula: "C(CH₃)₄",
    factor: 0.247,
    names: { en: "2,2-Dimethylpropane" },
    category: "common",
    searchKey: "2-2-dimethylpropane c(ch3)4 2,2-dimethylpropane",
  },
  {
    id: "3-methyl-1-butene",
    formula: "C₅H₁O",
    factor: 0.252,
    names: { en: "3-Methyl-1-butene" },
    category: "specialty",
    searchKey: "3-methyl-1-butene c5h1o 3-methyl-1-butene",
  },
  {
    id: "acetonitrile",
    formula: "C₂H₃N",
    factor: 0.51,
    names: { en: "Acetonitrile" },
    category: "specialty",
    searchKey: "acetonitrile c2h3n acetonitrile",
  },
  {
    id: "acetylene-ethyne",
    formula: "C₂H₂",
    factor: 0.615,
    names: { en: "Acetylene (Ethyne)" },
    category: "common",
    searchKey: "acetylene-ethyne c2h2 acetylene (ethyne)",
  },
  {
    id: "acrolein",
    formula: "C₃H₄O",
    factor: 0.362,
    names: { en: "Acrolein" },
    category: "specialty",
    searchKey: "acrolein c3h4o acrolein",
  },
  {
    id: "allene",
    formula: "C₃H₄",
    factor: 0.478,
    names: { en: "Allene" },
    category: "common",
    searchKey: "allene c3h4 allene",
  },
  {
    id: "ammonia",
    formula: "NH₃",
    factor: 0.786,
    names: { en: "Ammonia" },
    category: "common",
    searchKey: "ammonia nh3 ammonia",
  },
  {
    id: "arsine",
    formula: "AsH₃",
    factor: 0.754,
    names: { en: "Arsine" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "arsine ash3 arsine",
  },
  {
    id: "benzene",
    formula: "C₆H₆",
    factor: 0.294,
    names: { en: "Benzene" },
    category: "specialty",
    searchKey: "benzene c6h6 benzene",
  },
  {
    id: "borane",
    formula: "H₃B",
    factor: 0.778,
    names: { en: "Borane" },
    category: "specialty",
    searchKey: "borane h3b borane",
  },
  {
    id: "boron-trichloride",
    formula: "BCl₃",
    factor: 0.443,
    names: { en: "Boron Trichloride" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "boron-trichloride bcl3 boron trichloride",
  },
  {
    id: "boron-trifluoride",
    formula: "BF₃",
    factor: 0.579,
    names: { en: "Boron Trifluoride" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "boron-trifluoride bf3 boron trifluoride",
  },
  {
    id: "bromine",
    formula: "Br₂",
    factor: 0.8,
    names: { en: "Bromine" },
    category: "specialty",
    searchKey: "bromine br2 bromine",
  },
  {
    id: "bromine-pentafluoride",
    formula: "BrF₅",
    factor: 0.287,
    names: { en: "Bromine Pentafluoride" },
    category: "specialty",
    sealNote: "teflon",
    searchKey: "bromine-pentafluoride brf5 bromine pentafluoride",
  },
  {
    id: "bromine-trifluoride",
    formula: "BrF₃",
    factor: 0.439,
    names: { en: "Bromine Trifluoride" },
    category: "specialty",
    sealNote: "teflon",
    searchKey: "bromine-trifluoride brf3 bromine trifluoride",
  },
  {
    id: "bromotrifluoroethylene",
    formula: "C₂BrF₃",
    factor: 0.326,
    names: { en: "Bromotrifluoroethylene" },
    category: "common",
    searchKey: "bromotrifluoroethylene c2brf3 bromotrifluoroethylene",
  },
  {
    id: "bromotrifluoromethane-f13b1",
    formula: "CBrF₃",
    factor: 0.412,
    names: { en: "Bromotrifluoromethane (f13B1)" },
    category: "common",
    searchKey:
      "bromotrifluoromethane-f13b1 cbrf3 bromotrifluoromethane (f13b1)",
  },
  {
    id: "butane",
    formula: "C₄H₁O",
    factor: 0.257,
    names: { en: "Butane" },
    category: "common",
    searchKey: "butane c4h1o butane",
  },
  {
    id: "carbon-disulfide",
    formula: "CS₂",
    factor: 0.638,
    names: { en: "Carbon Disulfide" },
    category: "common",
    searchKey: "carbon-disulfide cs2 carbon disulfide",
  },
  {
    id: "carbon-monoxide",
    formula: "CO",
    factor: 0.995,
    names: { en: "Carbon Monoxide" },
    category: "specialty",
    searchKey: "carbon-monoxide co carbon monoxide",
  },
  {
    id: "carbon-tetrachloride",
    formula: "CCl₄",
    factor: 0.344,
    names: { en: "Carbon Tetrachloride" },
    category: "common",
    searchKey: "carbon-tetrachloride ccl4 carbon tetrachloride",
  },
  {
    id: "carbon-tetrachloride-f14",
    formula: "CF₄",
    factor: 0.44,
    names: { en: "Carbon Tetrachloride (f14)" },
    category: "common",
    searchKey: "carbon-tetrachloride-f14 cf4 carbon tetrachloride (f14)",
  },
  {
    id: "carbonyl-fluoride",
    formula: "COF₂",
    factor: 0.567,
    names: { en: "Carbonyl Fluoride" },
    category: "common",
    searchKey: "carbonyl-fluoride cof2 carbonyl fluoride",
  },
  {
    id: "carbonyl-sulfide",
    formula: "COS",
    factor: 0.68,
    names: { en: "Carbonyl Sulfide" },
    category: "common",
    searchKey: "carbonyl-sulfide cos carbonyl sulfide",
  },
  {
    id: "chlorine",
    formula: "Cl₂",
    factor: 0.876,
    names: { en: "Chlorine" },
    category: "common",
    searchKey: "chlorine cl2 chlorine",
  },
  {
    id: "chlorine-dioxide",
    formula: "ClO₂",
    factor: 0.693,
    names: { en: "Chlorine Dioxide" },
    category: "common",
    searchKey: "chlorine-dioxide clo2 chlorine dioxide",
  },
  {
    id: "chlorine-trifluoride",
    formula: "ClF₃",
    factor: 0.433,
    names: { en: "Chlorine Trifluoride" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "chlorine-trifluoride clf3 chlorine trifluoride",
  },
  {
    id: "chlorodifluoromethane-f22",
    formula: "CHClF₂",
    factor: 0.505,
    names: { en: "Chlorodifluoromethane (f22)" },
    category: "common",
    searchKey: "chlorodifluoromethane-f22 chclf2 chlorodifluoromethane (f22)",
  },
  {
    id: "chloroform-trichloromethane",
    formula: "CHCl₃",
    factor: 0.442,
    names: { en: "Chloroform (Trichloromethane)" },
    category: "common",
    searchKey:
      "chloroform-trichloromethane chcl3 chloroform (trichloromethane)",
  },
  {
    id: "chloropentafluoroethane-f115",
    formula: "C₂ClF₅",
    factor: 0.243,
    names: { en: "Chloropentafluoroethane (f115)" },
    category: "common",
    searchKey:
      "chloropentafluoroethane-f115 c2clf5 chloropentafluoroethane (f115)",
  },
  {
    id: "chlorotrifluoroethylene",
    formula: "C₂ClF₃",
    factor: 0.337,
    names: { en: "Chlorotrifluoroethylene" },
    category: "specialty",
    sealNote: "teflon",
    searchKey: "chlorotrifluoroethylene c2clf3 chlorotrifluoroethylene",
  },
  {
    id: "chlorotrifluoromethane-f13",
    formula: "CClF₃",
    factor: 0.43,
    names: { en: "Chlorotrifluoromethane (f13)" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "chlorotrifluoromethane-f13 cclf3 chlorotrifluoromethane (f13)",
  },
  {
    id: "cis-2-butene",
    formula: "C₄H₈",
    factor: 0.32,
    names: { en: "CIS-2-Butene" },
    category: "common",
    searchKey: "cis-2-butene c4h8 cis-2-butene",
  },
  {
    id: "cyanogen",
    formula: "(CN)₂",
    factor: 0.498,
    names: { en: "Cyanogen" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "cyanogen (cn)2 cyanogen",
  },
  {
    id: "cyanogen-chloride",
    formula: "ClCN",
    factor: 0.618,
    names: { en: "Cyanogen Chloride" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "cyanogen-chloride clcn cyanogen chloride",
  },
  {
    id: "cyclobutane",
    formula: "C₄H₈",
    factor: 0.387,
    names: { en: "Cyclobutane" },
    category: "common",
    searchKey: "cyclobutane c4h8 cyclobutane",
  },
  {
    id: "cyclopropane",
    formula: "C₃H₆",
    factor: 0.505,
    names: { en: "Cyclopropane" },
    category: "common",
    searchKey: "cyclopropane c3h6 cyclopropane",
  },
  {
    id: "deuterium",
    formula: "D₂",
    factor: 0.995,
    names: { en: "Deuterium" },
    category: "common",
    searchKey: "deuterium d2 deuterium",
  },
  {
    id: "diabromodifluoromethane-f12b2",
    formula: "CBr₂F₂",
    factor: 0.363,
    names: { en: "Diabromodifluoromethane (f12B2)" },
    category: "common",
    searchKey:
      "diabromodifluoromethane-f12b2 cbr2f2 diabromodifluoromethane (f12b2)",
  },
  {
    id: "diborane",
    formula: "B₂H₆",
    factor: 0.448,
    names: { en: "Diborane" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "diborane b2h6 diborane",
  },
  {
    id: "dichlorodifluoromethane-f12",
    formula: "CCl₂F₂",
    factor: 0.39,
    names: { en: "Dichlorodifluoromethane (f12)" },
    category: "common",
    searchKey:
      "dichlorodifluoromethane-f12 ccl2f2 dichlorodifluoromethane (f12)",
  },
  {
    id: "dichloroethylene",
    formula: "C₂H₂Cl₂",
    factor: 0.397,
    names: { en: "Dichloroethylene" },
    category: "specialty",
    searchKey: "dichloroethylene c2h2cl2 dichloroethylene",
  },
  {
    id: "dichlorofluoromethane-f21",
    formula: "CHCl₂F",
    factor: 0.456,
    names: { en: "Dichlorofluoromethane (f21)" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "dichlorofluoromethane-f21 chcl2f dichlorofluoromethane (f21)",
  },
  {
    id: "dichloromethane",
    formula: "CH₂Cl₂",
    factor: 0.522,
    names: { en: "Dichloromethane" },
    category: "specialty",
    searchKey: "dichloromethane ch2cl2 dichloromethane",
  },
  {
    id: "dichlorosilane",
    formula: "SiH₂Cl₂",
    factor: 0.442,
    names: { en: "Dichlorosilane" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "dichlorosilane sih2cl2 dichlorosilane",
  },
  {
    id: "diethylamine",
    formula: "C₄H₁N",
    factor: 0.222,
    names: { en: "Diethylamine" },
    category: "specialty",
    searchKey: "diethylamine c4h1n diethylamine",
  },
  {
    id: "diethylsilane",
    formula: "C₄H₁₂Si",
    factor: 0.183,
    names: { en: "Diethylsilane" },
    category: "specialty",
    searchKey: "diethylsilane c4h12si diethylsilane",
  },
  {
    id: "difluoromethane-r32",
    formula: "CF₂H₂",
    factor: 0.627,
    names: { en: "Difluoromethane (R32)" },
    category: "specialty",
    searchKey: "difluoromethane-r32 cf2h2 difluoromethane (r32)",
  },
  {
    id: "dimethylamine",
    formula: "(CH₃)₂NH",
    factor: 0.37,
    names: { en: "Dimethylamine" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "dimethylamine (ch3)2nh dimethylamine",
  },
  {
    id: "dimethylether",
    formula: "(CH₃)₂O",
    factor: 0.392,
    names: { en: "Dimethylether" },
    category: "common",
    searchKey: "dimethylether (ch3)2o dimethylether",
  },
  {
    id: "dimethylsulfide",
    formula: "C₂H₆S",
    factor: 0.357,
    names: { en: "Dimethylsulfide" },
    category: "specialty",
    searchKey: "dimethylsulfide c2h6s dimethylsulfide",
  },
  {
    id: "dimethylzinc",
    formula: "C₂H₆Zn",
    factor: 0.234,
    names: { en: "Dimethylzinc" },
    category: "specialty",
    searchKey: "dimethylzinc c2h6zn dimethylzinc",
  },
  {
    id: "disilane",
    formula: "Si₂H₆",
    factor: 0.332,
    names: { en: "Disilane" },
    category: "specialty",
    sealNote: "teflon",
    searchKey: "disilane si2h6 disilane",
  },
  {
    id: "ethane",
    formula: "C₂H₆",
    factor: 0.49,
    names: { en: "Ethane" },
    category: "common",
    searchKey: "ethane c2h6 ethane",
  },
  {
    id: "ethanol",
    formula: "C₂H₆O",
    factor: 0.394,
    names: { en: "Ethanol" },
    category: "specialty",
    searchKey: "ethanol c2h6o ethanol",
  },
  {
    id: "ethyl-chloride",
    formula: "C₂H₅Cl",
    factor: 0.408,
    names: { en: "Ethyl chloride" },
    category: "common",
    searchKey: "ethyl-chloride c2h5cl ethyl chloride",
  },
  {
    id: "ethylacetylene",
    formula: "C₄H₆",
    factor: 0.365,
    names: { en: "Ethylacetylene" },
    category: "common",
    searchKey: "ethylacetylene c4h6 ethylacetylene",
  },
  {
    id: "ethylene",
    formula: "C₂H₄",
    factor: 0.619,
    names: { en: "Ethylene" },
    category: "common",
    searchKey: "ethylene c2h4 ethylene",
  },
  {
    id: "ethylene-oxide",
    formula: "C₂H₄O",
    factor: 0.589,
    names: { en: "Ethylene Oxide" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "ethylene-oxide c2h4o ethylene oxide",
  },
  {
    id: "fluorine",
    formula: "F₂",
    factor: 0.924,
    names: { en: "Fluorine" },
    category: "specialty",
    sealNote: "metal",
    searchKey: "fluorine f2 fluorine",
  },
  {
    id: "fluoroform-f23",
    formula: "CHF₃",
    factor: 0.529,
    names: { en: "Fluoroform (f23)" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "fluoroform-f23 chf3 fluoroform (f23)",
  },
  {
    id: "germanium-tetrachloride",
    formula: "GeCl₄",
    factor: 0.268,
    names: { en: "Germanium Tetrachloride" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "germanium-tetrachloride gecl4 germanium tetrachloride",
  },
  {
    id: "germanium-tetrafluoride",
    formula: "GeF₄",
    factor: 0.356,
    names: { en: "Germanium Tetrafluoride" },
    category: "specialty",
    searchKey: "germanium-tetrafluoride gef4 germanium tetrafluoride",
  },
  {
    id: "germanium-tetrahydride-germane",
    formula: "GeH₄",
    factor: 0.559,
    names: { en: "Germanium Tetrahydride (Germane)" },
    category: "specialty",
    searchKey:
      "germanium-tetrahydride-germane geh4 germanium tetrahydride (germane)",
  },
  {
    id: "halothane-r123b1",
    formula: "C₂HBrClF₃",
    factor: 0.257,
    names: { en: "Halothane (R123B1)" },
    category: "specialty",
    searchKey: "halothane-r123b1 c2hbrclf3 halothane (r123b1)",
  },
  {
    id: "hexafluoroacetone",
    formula: "C₃F₆O",
    factor: 0.219,
    names: { en: "Hexafluoroacetone" },
    category: "specialty",
    searchKey: "hexafluoroacetone c3f6o hexafluoroacetone",
  },
  {
    id: "hexafluorobenzine",
    formula: "C₆F₆",
    factor: 0.632,
    names: { en: "Hexafluorobenzine" },
    category: "specialty",
    searchKey: "hexafluorobenzine c6f6 hexafluorobenzine",
  },
  {
    id: "hexafluorobutadiene",
    formula: "C₄F₆",
    factor: 0.213,
    names: { en: "Hexafluorobutadiene" },
    category: "specialty",
    searchKey: "hexafluorobutadiene c4f6 hexafluorobutadiene",
  },
  {
    id: "hexafluoroethane-f116",
    formula: "C₂F₆",
    factor: 0.255,
    names: { en: "Hexafluoroethane (f116)" },
    category: "common",
    searchKey: "hexafluoroethane-f116 c2f6 hexafluoroethane (f116)",
  },
  {
    id: "hexafluoropropylene-hfp",
    formula: "C₃F₆",
    factor: 0.249,
    names: { en: "Hexafluoropropylene (HFP)" },
    category: "common",
    searchKey: "hexafluoropropylene-hfp c3f6 hexafluoropropylene (hfp)",
  },
  {
    id: "hexamethyldisilane-hmds",
    formula: "(CH₂)₆Si₂",
    factor: 0.139,
    names: { en: "Hexamethyldisilane (HMDS)" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "hexamethyldisilane-hmds (ch2)6si2 hexamethyldisilane (hmds)",
  },
  {
    id: "hexamethyldisiloxane",
    formula: "C₆H₁₈OSi₂",
    factor: 0.11,
    names: { en: "Hexamethyldisiloxane" },
    category: "specialty",
    searchKey: "hexamethyldisiloxane c6h18osi2 hexamethyldisiloxane",
  },
  {
    id: "hexane",
    formula: "C₆H₁₄",
    factor: 0.204,
    names: { en: "Hexane" },
    category: "common",
    searchKey: "hexane c6h14 hexane",
  },
  {
    id: "hexylamine",
    formula: "C₆H₁₅N",
    factor: 0.158,
    names: { en: "Hexylamine" },
    category: "specialty",
    searchKey: "hexylamine c6h15n hexylamine",
  },
  {
    id: "hydrogen-bromide",
    formula: "HBr",
    factor: 0.987,
    names: { en: "Hydrogen Bromide" },
    category: "common",
    searchKey: "hydrogen-bromide hbr hydrogen bromide",
  },
  {
    id: "hydrogen-chloride",
    formula: "HCl",
    factor: 0.983,
    names: { en: "Hydrogen Chloride" },
    category: "common",
    searchKey: "hydrogen-chloride hcl hydrogen chloride",
  },
  {
    id: "hydrogen-cyanide",
    formula: "HCN",
    factor: 0.744,
    names: { en: "Hydrogen Cyanide" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "hydrogen-cyanide hcn hydrogen cyanide",
  },
  {
    id: "hydrogen-fluoride",
    formula: "HF",
    factor: 0.998,
    names: { en: "Hydrogen Fluoride" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "hydrogen-fluoride hf hydrogen fluoride",
  },
  {
    id: "hydrogen-iodide",
    formula: "HI",
    factor: 0.953,
    names: { en: "Hydrogen Iodide" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "hydrogen-iodide hi hydrogen iodide",
  },
  {
    id: "hydrogen-selenide",
    formula: "H₂Se",
    factor: 0.837,
    names: { en: "Hydrogen Selenide" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "hydrogen-selenide h2se hydrogen selenide",
  },
  {
    id: "hydrogen-sulfide",
    formula: "H₂S",
    factor: 0.85,
    names: { en: "Hydrogen Sulfide" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "hydrogen-sulfide h2s hydrogen sulfide",
  },
  {
    id: "iodine-pentafluoride",
    formula: "IF₅",
    factor: 0.283,
    names: { en: "Iodine Pentafluoride" },
    category: "specialty",
    sealNote: "teflon",
    searchKey: "iodine-pentafluoride if5 iodine pentafluoride",
  },
  {
    id: "isobutane",
    formula: "C₄H₁O",
    factor: 0.26,
    names: { en: "Isobutane" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "isobutane c4h1o isobutane",
  },
  {
    id: "isobutene",
    formula: "C₄H₈",
    factor: 0.289,
    names: { en: "Isobutene" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "isobutene c4h8 isobutene",
  },
  {
    id: "isopentane",
    formula: "C₅H₁₂",
    factor: 0.211,
    names: { en: "Isopentane" },
    category: "specialty",
    searchKey: "isopentane c5h12 isopentane",
  },
  {
    id: "krypton",
    formula: "Kr",
    factor: 1.382,
    names: { en: "Krypton" },
    category: "common",
    searchKey: "krypton kr krypton",
  },
  {
    id: "methacrolein",
    formula: "C₄H₆O",
    factor: 0.313,
    names: { en: "Methacrolein" },
    category: "specialty",
    searchKey: "methacrolein c4h6o methacrolein",
  },
  {
    id: "methane",
    formula: "CH₄",
    factor: 0.763,
    names: { en: "Methane" },
    category: "common",
    searchKey: "methane ch4 methane",
  },
  {
    id: "methanol",
    formula: "CH₄O",
    factor: 0.609,
    names: { en: "Methanol" },
    category: "specialty",
    searchKey: "methanol ch4o methanol",
  },
  {
    id: "methyl-bromide",
    formula: "CH₃Br",
    factor: 0.646,
    names: { en: "Methyl Bromide" },
    category: "specialty",
    searchKey: "methyl-bromide ch3br methyl bromide",
  },
  {
    id: "methyl-chloride",
    formula: "CH₃Cl",
    factor: 0.687,
    names: { en: "Methyl Chloride" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "methyl-chloride ch3cl methyl chloride",
  },
  {
    id: "methyl-fluoride",
    formula: "CH₃F",
    factor: 0.761,
    names: { en: "Methyl Fluoride" },
    category: "specialty",
    searchKey: "methyl-fluoride ch3f methyl fluoride",
  },
  {
    id: "methyl-mercaptan",
    formula: "CH₄S",
    factor: 0.588,
    names: { en: "Methyl Mercaptan" },
    category: "specialty",
    searchKey: "methyl-mercaptan ch4s methyl mercaptan",
  },
  {
    id: "methyl-silane",
    formula: "CH₆Si",
    factor: 0.393,
    names: { en: "Methyl Silane" },
    category: "specialty",
    searchKey: "methyl-silane ch6si methyl silane",
  },
  {
    id: "methyl-trichlorosilane-mts",
    formula: "CH₃Cl₃Si",
    factor: 0.267,
    names: { en: "Methyl Trichlorosilane (MTS)" },
    category: "specialty",
    searchKey:
      "methyl-trichlorosilane-mts ch3cl3si methyl trichlorosilane (mts)",
  },
  {
    id: "methyl-vinyl-ether",
    formula: "C₃H₆O",
    factor: 0.337,
    names: { en: "Methyl Vinyl Ether" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "methyl-vinyl-ether c3h6o methyl vinyl ether",
  },
  {
    id: "methylacetylene",
    formula: "C₃H₄",
    factor: 0.473,
    names: { en: "Methylacetylene" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "methylacetylene c3h4 methylacetylene",
  },
  {
    id: "monoethyanolamine",
    formula: "C₂H₇NO",
    factor: 0.305,
    names: { en: "Monoethyanolamine" },
    category: "specialty",
    searchKey: "monoethyanolamine c2h7no monoethyanolamine",
  },
  {
    id: "monoethylamine-ch3ch2nh2",
    formula: "C₂H₇",
    factor: 0.395,
    names: { en: "Monoethylamine (CH3CH2NH2)" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "monoethylamine-ch3ch2nh2 c2h7 monoethylamine (ch3ch2nh2)",
  },
  {
    id: "monomethylamine",
    formula: "CH₃NH₂",
    factor: 0.565,
    names: { en: "Monomethylamine" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "monomethylamine ch3nh2 monomethylamine",
  },
  {
    id: "neon",
    formula: "Ne",
    factor: 1.398,
    names: { en: "Neon" },
    category: "common",
    searchKey: "neon ne neon",
  },
  {
    id: "nickel-carbonyl",
    formula: "Ni(CO)₄",
    factor: 0.212,
    names: { en: "Nickel Carbonyl" },
    category: "specialty",
    searchKey: "nickel-carbonyl ni(co)4 nickel carbonyl",
  },
  {
    id: "nitric-acid",
    formula: "HNO₃",
    factor: 0.491,
    names: { en: "Nitric Acid" },
    category: "specialty",
    searchKey: "nitric-acid hno3 nitric acid",
  },
  {
    id: "nitric-oxide",
    formula: "NO",
    factor: 0.995,
    names: { en: "Nitric Oxide" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "nitric-oxide no nitric oxide",
  },
  {
    id: "nitrogen-dioxide",
    formula: "NO₂",
    factor: 0.758,
    names: { en: "Nitrogen Dioxide" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "nitrogen-dioxide no2 nitrogen dioxide",
  },
  {
    id: "nitrogen-trifluoride",
    formula: "NF₃",
    factor: 0.501,
    names: { en: "Nitrogen Trifluoride" },
    category: "specialty",
    sealNote: "teflon",
    searchKey: "nitrogen-trifluoride nf3 nitrogen trifluoride",
  },
  {
    id: "nitrogen-trioxide",
    formula: "N₂O₃",
    factor: 0.443,
    names: { en: "Nitrogen Trioxide" },
    category: "specialty",
    searchKey: "nitrogen-trioxide n2o3 nitrogen trioxide",
  },
  {
    id: "nitrosyl-chloride",
    formula: "NOCl",
    factor: 0.664,
    names: { en: "Nitrosyl Chloride" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "nitrosyl-chloride nocl nitrosyl chloride",
  },
  {
    id: "nitrous-oxide",
    formula: "N₂O",
    factor: 0.752,
    names: { en: "Nitrous Oxide" },
    category: "common",
    searchKey: "nitrous-oxide n2o nitrous oxide",
  },
  {
    id: "octofluorocyclobutane",
    formula: "C₄F₈",
    factor: 0.169,
    names: { en: "Octofluorocyclobutane" },
    category: "specialty",
    searchKey: "octofluorocyclobutane c4f8 octofluorocyclobutane",
  },
  {
    id: "octofluorotetrahydrofuran",
    formula: "C₄F₈O",
    factor: 0.165,
    names: { en: "Octofluorotetrahydrofuran" },
    category: "specialty",
    searchKey: "octofluorotetrahydrofuran c4f8o octofluorotetrahydrofuran",
  },
  {
    id: "oxygen-difluoride",
    formula: "OF₂",
    factor: 0.672,
    names: { en: "Oxygen Difluoride" },
    category: "specialty",
    searchKey: "oxygen-difluoride of2 oxygen difluoride",
  },
  {
    id: "ozone",
    formula: "O₃",
    factor: 0.738,
    names: { en: "Ozone" },
    category: "common",
    searchKey: "ozone o3 ozone",
  },
  {
    id: "pentafluoroethane",
    formula: "C₂HF₅",
    factor: 0.287,
    names: { en: "Pentafluoroethane" },
    category: "specialty",
    searchKey: "pentafluoroethane c2hf5 pentafluoroethane",
  },
  {
    id: "pentane-n-pentane",
    formula: "C₅H₁₂",
    factor: 0.212,
    names: { en: "Pentane (n-Pentane)" },
    category: "specialty",
    searchKey: "pentane-n-pentane c5h12 pentane (n-pentane)",
  },
  {
    id: "perchlory-fluoride",
    formula: "ClO₃F",
    factor: 0.448,
    names: { en: "Perchlory Fluoride" },
    category: "specialty",
    searchKey: "perchlory-fluoride clo3f perchlory fluoride",
  },
  {
    id: "perfluoro-2-butene",
    formula: "C₄F₈",
    factor: 0.268,
    names: { en: "Perfluoro-2-Butene" },
    category: "specialty",
    searchKey: "perfluoro-2-butene c4f8 perfluoro-2-butene",
  },
  {
    id: "perfluorobutane",
    formula: "C₄F₁₀",
    factor: 0.738,
    names: { en: "Perfluorobutane" },
    category: "specialty",
    searchKey: "perfluorobutane c4f10 perfluorobutane",
  },
  {
    id: "perfluoromethyl-vinylether-pmve",
    formula: "PMVE",
    factor: 0.296,
    names: { en: "Perfluoromethyl-Vinylether (PMVE)" },
    category: "specialty",
    searchKey:
      "perfluoromethyl-vinylether-pmve pmve perfluoromethyl-vinylether (pmve)",
  },
  {
    id: "perfluoropropane",
    formula: "C₃F₈",
    factor: 0.179,
    names: { en: "Perfluoropropane" },
    category: "specialty",
    searchKey: "perfluoropropane c3f8 perfluoropropane",
  },
  {
    id: "phosgene",
    formula: "COCl₂",
    factor: 0.504,
    names: { en: "Phosgene" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "phosgene cocl2 phosgene",
  },
  {
    id: "phosphine",
    formula: "PH₃",
    factor: 0.783,
    names: { en: "Phosphine" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "phosphine ph3 phosphine",
  },
  {
    id: "phosphorous-oxychloride",
    formula: "POCl₃",
    factor: 0.327,
    names: { en: "Phosphorous Oxychloride" },
    category: "specialty",
    searchKey: "phosphorous-oxychloride pocl3 phosphorous oxychloride",
  },
  {
    id: "phosphorous-pentafluoride",
    formula: "PF₅",
    factor: 0.346,
    names: { en: "Phosphorous Pentafluoride" },
    category: "specialty",
    searchKey: "phosphorous-pentafluoride pf5 phosphorous pentafluoride",
  },
  {
    id: "phosphorous-trifluoride",
    formula: "PF₃",
    factor: 0.495,
    names: { en: "Phosphorous Trifluoride" },
    category: "specialty",
    searchKey: "phosphorous-trifluoride pf3 phosphorous trifluoride",
  },
  {
    id: "propadiene",
    formula: "C₃H₄",
    factor: 0.439,
    names: { en: "Propadiene" },
    category: "specialty",
    searchKey: "propadiene c3h4 propadiene",
  },
  {
    id: "propane-same-as-ch3ch2ch3",
    formula: "C₃H₈",
    factor: 0.343,
    names: { en: "Propane (same as CH3CH2CH3)" },
    category: "common",
    searchKey: "propane-same-as-ch3ch2ch3 c3h8 propane (same as ch3ch2ch3)",
  },
  {
    id: "propylene-propene",
    formula: "C₃H₆",
    factor: 0.401,
    names: { en: "Propylene (Propene)*" },
    category: "common",
    searchKey: "propylene-propene c3h6 propylene (propene)*",
  },
  {
    id: "rhenium-hexafluoride",
    formula: "ReF₆",
    factor: 0.23,
    names: { en: "Rhenium Hexafluoride" },
    category: "specialty",
    searchKey: "rhenium-hexafluoride ref6 rhenium hexafluoride",
  },
  {
    id: "silane",
    formula: "SiH₄",
    factor: 0.625,
    names: { en: "Silane" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "silane sih4 silane",
  },
  {
    id: "silicon-tetrachloride",
    formula: "SiCl₄",
    factor: 0.31,
    names: { en: "Silicon Tetrachloride" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "silicon-tetrachloride sicl4 silicon tetrachloride",
  },
  {
    id: "silicon-tetrafluoride",
    formula: "SiF₄",
    factor: 0.395,
    names: { en: "Silicon Tetrafluoride" },
    category: "specialty",
    sealNote: "teflon",
    searchKey: "silicon-tetrafluoride sif4 silicon tetrafluoride",
  },
  {
    id: "sulfur-dioxide",
    formula: "SO₂",
    factor: 0.728,
    names: { en: "Sulfur Dioxide" },
    category: "common",
    searchKey: "sulfur-dioxide so2 sulfur dioxide",
  },
  {
    id: "sulfur-hexafluoride",
    formula: "SF₆",
    factor: 0.27,
    names: { en: "Sulfur Hexafluoride" },
    category: "common",
    searchKey: "sulfur-hexafluoride sf6 sulfur hexafluoride",
  },
  {
    id: "sulfur-tetrafluoride",
    formula: "SF₄",
    factor: 0.353,
    names: { en: "Sulfur Tetrafluoride" },
    category: "specialty",
    searchKey: "sulfur-tetrafluoride sf4 sulfur tetrafluoride",
  },
  {
    id: "sulfur-trioxide",
    formula: "SO₃",
    factor: 0.535,
    names: { en: "Sulfur Trioxide" },
    category: "specialty",
    searchKey: "sulfur-trioxide so3 sulfur trioxide",
  },
  {
    id: "sulfuryl-fluoride",
    formula: "SO₂F₂",
    factor: 0.423,
    names: { en: "Sulfuryl Fluoride" },
    category: "specialty",
    searchKey: "sulfuryl-fluoride so2f2 sulfuryl fluoride",
  },
  {
    id: "tetrachloromethane",
    formula: "CCl₄",
    factor: 0.344,
    names: { en: "Tetrachloromethane" },
    category: "specialty",
    searchKey: "tetrachloromethane ccl4 tetrachloromethane",
  },
  {
    id: "tetraethylsilane",
    formula: "C₈H₂₀Si",
    factor: 0.111,
    names: { en: "Tetraethylsilane" },
    category: "specialty",
    searchKey: "tetraethylsilane c8h20si tetraethylsilane",
  },
  {
    id: "tetrafluoroethylene-tfe",
    formula: "C₂F₄",
    factor: 0.361,
    names: { en: "Tetrafluoroethylene (TFE)" },
    category: "common",
    searchKey: "tetrafluoroethylene-tfe c2f4 tetrafluoroethylene (tfe)",
  },
  {
    id: "tetrafluorohydrazine",
    formula: "N₂F₄",
    factor: 0.367,
    names: { en: "Tetrafluorohydrazine" },
    category: "specialty",
    searchKey: "tetrafluorohydrazine n2f4 tetrafluorohydrazine",
  },
  {
    id: "tetramethylsilane",
    formula: "C₄H₁₂Si",
    factor: 0.183,
    names: { en: "Tetramethylsilane" },
    category: "specialty",
    searchKey: "tetramethylsilane c4h12si tetramethylsilane",
  },
  {
    id: "titanium-tetrachloride",
    formula: "TiCl₄",
    factor: 0.296,
    names: { en: "Titanium Tetrachloride" },
    category: "specialty",
    searchKey: "titanium-tetrachloride ticl4 titanium tetrachloride",
  },
  {
    id: "toluene-c6h5",
    formula: "CH₃",
    factor: 0.234,
    names: { en: "Toluene (C6H5)" },
    category: "specialty",
    searchKey: "toluene-c6h5 ch3 toluene (c6h5)",
  },
  {
    id: "trans-2-butene",
    formula: "C₄H₈",
    factor: 0.291,
    names: { en: "Trans-2-Butene" },
    category: "specialty",
    searchKey: "trans-2-butene c4h8 trans-2-butene",
  },
  {
    id: "trichlorofluoromethane-f11",
    formula: "CCl₃F",
    factor: 0.374,
    names: { en: "Trichlorofluoromethane (f11)" },
    category: "specialty",
    sealNote: "teflon",
    searchKey: "trichlorofluoromethane-f11 ccl3f trichlorofluoromethane (f11)",
  },
  {
    id: "trichlorosilane",
    formula: "SiHCl₃",
    factor: 0.329,
    names: { en: "Trichlorosilane" },
    category: "common",
    searchKey: "trichlorosilane sihcl3 trichlorosilane",
  },
  {
    id: "trifluoroethane",
    formula: "C₂F₃F₃",
    factor: 0.333,
    names: { en: "Trifluoroethane" },
    category: "specialty",
    searchKey: "trifluoroethane c2f3f3 trifluoroethane",
  },
  {
    id: "trifluoropropene",
    formula: "C₃H₃F₃",
    factor: 0.286,
    names: { en: "Trifluoropropene" },
    category: "specialty",
    searchKey: "trifluoropropene c3h3f3 trifluoropropene",
  },
  {
    id: "trimethyl-aluminum",
    formula: "C₃H₉Al",
    factor: 0.259,
    names: { en: "Trimethyl Aluminum" },
    category: "specialty",
    searchKey: "trimethyl-aluminum c3h9al trimethyl aluminum",
  },
  {
    id: "trimethylamine",
    formula: "(CH₃)₃N",
    factor: 0.316,
    names: { en: "Trimethylamine" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "trimethylamine (ch3)3n trimethylamine",
  },
  {
    id: "trimethylgallium",
    formula: "C₃H₉Ga",
    factor: 0.237,
    names: { en: "Trimethylgallium" },
    category: "specialty",
    searchKey: "trimethylgallium c3h9ga trimethylgallium",
  },
  {
    id: "trimethyloxyborane-tmb",
    formula: "B(OCH₃)₃",
    factor: 0.3,
    names: { en: "Trimethyloxyborane (TMB)" },
    category: "specialty",
    searchKey: "trimethyloxyborane-tmb b(och3)3 trimethyloxyborane (tmb)",
  },
  {
    id: "trimethylsilane",
    formula: "C₃H₁₀Si",
    factor: 0.235,
    names: { en: "Trimethylsilane" },
    category: "specialty",
    searchKey: "trimethylsilane c3h10si trimethylsilane",
  },
  {
    id: "tungsten-hexafluoride",
    formula: "WF₆",
    factor: 0.227,
    names: { en: "Tungsten Hexafluoride" },
    category: "specialty",
    sealNote: "teflon",
    searchKey: "tungsten-hexafluoride wf6 tungsten hexafluoride",
  },
  {
    id: "uranium-hexafluoride",
    formula: "UF₆",
    factor: 0.22,
    names: { en: "Uranium Hexafluoride" },
    category: "specialty",
    sealNote: "teflon",
    searchKey: "uranium-hexafluoride uf6 uranium hexafluoride",
  },
  {
    id: "vinyl-bromide",
    formula: "C₂H₃Br",
    factor: 0.524,
    names: { en: "Vinyl Bromide" },
    category: "specialty",
    searchKey: "vinyl-bromide c2h3br vinyl bromide",
  },
  {
    id: "vinyl-chloride",
    formula: "C₂H₃Cl",
    factor: 0.542,
    names: { en: "Vinyl Chloride" },
    category: "common",
    searchKey: "vinyl-chloride c2h3cl vinyl chloride",
  },
  {
    id: "vinyl-fluoride",
    formula: "C₂H₃F",
    factor: 0.576,
    names: { en: "Vinyl Fluoride" },
    category: "specialty",
    sealNote: "kalrez",
    searchKey: "vinyl-fluoride c2h3f vinyl fluoride",
  },
  {
    id: "water-vapor",
    formula: "H₂O",
    factor: 0.861,
    names: { en: "Water Vapor" },
    category: "specialty",
    searchKey: "water-vapor h2o water vapor",
  },
  {
    id: "xennon",
    formula: "Xe",
    factor: 1.383,
    names: { en: "Xennon" },
    category: "common",
    searchKey: "xennon xe xennon",
  },
];

/** Reference gas: N₂, factor 1.000. */
export const REFERENCE_GAS_ID = "nitrogen";

/** Lookup by id. Returns undefined if not found. */
export function getGasFactor(id: string): GasFactor | undefined {
  return GAS_FACTORS.find((g) => g.id === id);
}

/**
 * Fold Unicode subscript digits (U+2080..U+2089) in a query to ASCII so the
 * caller can match precomputed `searchKey` values regardless of how the user
 * typed the formula. Exported for tests.
 */
const SUB_DIGITS = /[\u2080-\u2089]/g;
export function normalizeGasQuery(query: string): string {
  return query
    .toLowerCase()
    .replace(SUB_DIGITS, (d) =>
      String.fromCharCode(d.charCodeAt(0) - 0x2080 + 0x30),
    );
}
