// AUTO-GENERATED FROM 2020 catalogue appendix (gas-conversion table).
// Source: docs/archive/2020-catalog/product-catalog-2020-en.md § 13.
// K-factors are physical constants; do not edit by hand.

export type GasCategory = "common" | "specialty";
export type GasSealNote = "kalrez" | "teflon" | "metal";

export type GasFactor = {
  /** kebab-case id, used in URL search params */
  id: string;
  /** typeset chemical formula, e.g. "N₂", "CO₂" */
  formula: string;
  /** K-factor relative to N₂ (= 1.000) */
  factor: number;
  /** English name (KO/ZH localization deferred to v1.1) */
  names: { en: string };
  /**
   * "common" = a standard elastomer (Viton/Buna/EPDM) is recommended for this gas;
   * "specialty" = needs Kalrez/Teflon/Metal seal — UI surfaces a verify-with-sales note.
   */
  category: GasCategory;
  /** Specific seal recommendation when category is "specialty". */
  sealNote?: GasSealNote;
  /** True for the seven gases pinned at the top of the picker. */
  pinned?: true;
};

export const GAS_FACTORS: readonly GasFactor[] = [
  {
    id: "nitrogen",
    formula: "N₂",
    factor: 1,
    names: { en: "Nitrogen" },
    category: "common",
    pinned: true,
  },
  {
    id: "oxygen",
    formula: "O₂",
    factor: 0.988,
    names: { en: "Oxygen" },
    category: "common",
    pinned: true,
  },
  {
    id: "argon",
    formula: "Ar",
    factor: 1.395,
    names: { en: "Argon" },
    category: "common",
    pinned: true,
  },
  {
    id: "helium",
    formula: "He",
    factor: 1.386,
    names: { en: "Helium" },
    category: "common",
    pinned: true,
  },
  {
    id: "hydrogen",
    formula: "H₂",
    factor: 1.008,
    names: { en: "Hydrogen" },
    category: "common",
    pinned: true,
  },
  {
    id: "air",
    formula: "Air",
    factor: 0.998,
    names: { en: "Air" },
    category: "common",
    pinned: true,
  },
  {
    id: "carbon-dioxide",
    formula: "CO₂",
    factor: 0.74,
    names: { en: "Carbon Dioxide" },
    category: "common",
    pinned: true,
  },
  {
    id: "1-butene",
    formula: "C₄H₈",
    factor: 0.294,
    names: { en: "1-Butene" },
    category: "common",
  },
  {
    id: "1-pentene-4-methyl",
    formula: "C₆H₁₂",
    factor: 0.2,
    names: { en: "1-Pentene, 4-Methyl" },
    category: "specialty",
  },
  {
    id: "1-1-difluoro-1-chloroethane",
    formula: "C₂H₃ClF₂",
    factor: 0.341,
    names: { en: "1,1-Difluoro-1-Chloroethane" },
    category: "common",
  },
  {
    id: "1-1-difluoroethane",
    formula: "CH₃CHF₂",
    factor: 0.415,
    names: { en: "1,1-Difluoroethane" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "1-1-difluoroethylene",
    formula: "CH₂:CF₂",
    factor: 0.458,
    names: { en: "1,1-Difluoroethylene" },
    category: "common",
  },
  {
    id: "1-1-1-2-tetrafluoroethane-r134a",
    formula: "C₂H₂F₄",
    factor: 0.307,
    names: { en: "1,1,1,2-Tetrafluoroethane (R134A)" },
    category: "common",
  },
  {
    id: "1-1-2-trichloro-1-1-2-trifluoroet-f113",
    formula: "C₂Cl₃F₃",
    factor: 0.231,
    names: { en: "1,1,2-Trichloro-1,1,2-Trifluoroet (f113)" },
    category: "common",
  },
  {
    id: "1-1-2-2-tetrafluoroethane-r134",
    formula: "C₂H₂F₄",
    factor: 0.295,
    names: { en: "1,1,2,2-Tetrafluoroethane (R134)" },
    category: "specialty",
  },
  {
    id: "1-2-dibromotetrafluoroethane-f114b2",
    formula: "C₂Br₂F₄",
    factor: 0.215,
    names: { en: "1,2-Dibromotetrafluoroethane (f114B2)" },
    category: "specialty",
    sealNote: "teflon",
  },
  {
    id: "1-2-dichloroethane-ethylene-dichloride",
    formula: "C₂H₄Cl₂",
    factor: 0.382,
    names: { en: "1,2-Dichloroethane (Ethylene dichloride)" },
    category: "common",
  },
  {
    id: "1-2-dichlorotetrafluoroethane-f114",
    formula: "C₂Cl₂F₄",
    factor: 0.231,
    names: { en: "1,2-Dichlorotetrafluoroethane (f114)" },
    category: "common",
  },
  {
    id: "1-2-propylene-oxide",
    formula: "C₃H₆O",
    factor: 0.348,
    names: { en: "1,2-Propylene Oxide" },
    category: "specialty",
  },
  {
    id: "1-3-butadiene",
    formula: "C₄H₆",
    factor: 0.354,
    names: { en: "1,3-Butadiene" },
    category: "common",
  },
  {
    id: "2-chloro-1-1-1-2-tetrafluoroethane-r124",
    formula: "C₂HCIF₄",
    factor: 0.027,
    names: { en: "2-Chloro-1,1,1,2-Tetrafluoroethane (R124)" },
    category: "specialty",
  },
  {
    id: "2-chlorobutane",
    formula: "C₄H₉Cl",
    factor: 0.234,
    names: { en: "2-Chlorobutane" },
    category: "specialty",
  },
  {
    id: "2-methyl-1-3-butadiene",
    formula: "C₅H₈",
    factor: 0.247,
    names: { en: "2-Methyl-1,3-Butadiene" },
    category: "specialty",
  },
  {
    id: "2-2-dichloro-1-1-1-trifloroethane",
    formula: "C₂HCl₂F₃",
    factor: 0.259,
    names: { en: "2,2-Dichloro-1,1,1-Trifloroethane" },
    category: "specialty",
  },
  {
    id: "2-2-dimethylpropane",
    formula: "C(CH₃)₄",
    factor: 0.247,
    names: { en: "2,2-Dimethylpropane" },
    category: "common",
  },
  {
    id: "3-methyl-1-butene",
    formula: "C₅H₁O",
    factor: 0.252,
    names: { en: "3-Methyl-1-butene" },
    category: "specialty",
  },
  {
    id: "acetonitrile",
    formula: "C₂H₃N",
    factor: 0.51,
    names: { en: "Acetonitrile" },
    category: "specialty",
  },
  {
    id: "acetylene-ethyne",
    formula: "C₂H₂",
    factor: 0.615,
    names: { en: "Acetylene (Ethyne)" },
    category: "common",
  },
  {
    id: "acrolein",
    formula: "C₃H₄O",
    factor: 0.362,
    names: { en: "Acrolein" },
    category: "specialty",
  },
  {
    id: "allene",
    formula: "C₃H₄",
    factor: 0.478,
    names: { en: "Allene" },
    category: "common",
  },
  {
    id: "ammonia",
    formula: "NH₃",
    factor: 0.786,
    names: { en: "Ammonia" },
    category: "common",
  },
  {
    id: "arsine",
    formula: "AsH₃",
    factor: 0.754,
    names: { en: "Arsine" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "benzene",
    formula: "C₆H₆",
    factor: 0.294,
    names: { en: "Benzene" },
    category: "specialty",
  },
  {
    id: "borane",
    formula: "H₃B",
    factor: 0.778,
    names: { en: "Borane" },
    category: "specialty",
  },
  {
    id: "boron-trichloride",
    formula: "BCl₃",
    factor: 0.443,
    names: { en: "Boron Trichloride" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "boron-trifluoride",
    formula: "BF₃",
    factor: 0.579,
    names: { en: "Boron Trifluoride" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "bromine",
    formula: "Br₂",
    factor: 0.8,
    names: { en: "Bromine" },
    category: "specialty",
  },
  {
    id: "bromine-pentafluoride",
    formula: "BrF₅",
    factor: 0.287,
    names: { en: "Bromine Pentafluoride" },
    category: "specialty",
    sealNote: "teflon",
  },
  {
    id: "bromine-trifluoride",
    formula: "BrF₃",
    factor: 0.439,
    names: { en: "Bromine Trifluoride" },
    category: "specialty",
    sealNote: "teflon",
  },
  {
    id: "bromotrifluoroethylene",
    formula: "C₂BrF₃",
    factor: 0.326,
    names: { en: "Bromotrifluoroethylene" },
    category: "common",
  },
  {
    id: "bromotrifluoromethane-f13b1",
    formula: "CBrF₃",
    factor: 0.412,
    names: { en: "Bromotrifluoromethane (f13B1)" },
    category: "common",
  },
  {
    id: "butane",
    formula: "C₄H₁O",
    factor: 0.257,
    names: { en: "Butane" },
    category: "common",
  },
  {
    id: "carbon-disulfide",
    formula: "CS₂",
    factor: 0.638,
    names: { en: "Carbon Disulfide" },
    category: "common",
  },
  {
    id: "carbon-monoxide",
    formula: "CO",
    factor: 0.995,
    names: { en: "Carbon Monoxide" },
    category: "specialty",
  },
  {
    id: "carbon-tetrachloride",
    formula: "CCl₄",
    factor: 0.344,
    names: { en: "Carbon Tetrachloride" },
    category: "common",
  },
  {
    id: "carbon-tetrachloride-f14",
    formula: "CF₄",
    factor: 0.44,
    names: { en: "Carbon Tetrachloride (f14)" },
    category: "common",
  },
  {
    id: "carbonyl-fluoride",
    formula: "COF₂",
    factor: 0.567,
    names: { en: "Carbonyl Fluoride" },
    category: "common",
  },
  {
    id: "carbonyl-sulfide",
    formula: "COS",
    factor: 0.68,
    names: { en: "Carbonyl Sulfide" },
    category: "common",
  },
  {
    id: "chlorine",
    formula: "Cl₂",
    factor: 0.876,
    names: { en: "Chlorine" },
    category: "common",
  },
  {
    id: "chlorine-dioxide",
    formula: "ClO₂",
    factor: 0.693,
    names: { en: "Chlorine Dioxide" },
    category: "common",
  },
  {
    id: "chlorine-trifluoride",
    formula: "ClF₃",
    factor: 0.433,
    names: { en: "Chlorine Trifluoride" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "chlorodifluoromethane-f22",
    formula: "CHClF₂",
    factor: 0.505,
    names: { en: "Chlorodifluoromethane (f22)" },
    category: "common",
  },
  {
    id: "chloroform-trichloromethane",
    formula: "CHCl₃",
    factor: 0.442,
    names: { en: "Chloroform (Trichloromethane)" },
    category: "common",
  },
  {
    id: "chloropentafluoroethane-f115",
    formula: "C₂ClF₅",
    factor: 0.243,
    names: { en: "Chloropentafluoroethane (f115)" },
    category: "common",
  },
  {
    id: "chlorotrifluoroethylene",
    formula: "C₂ClF₃",
    factor: 0.337,
    names: { en: "Chlorotrifluoroethylene" },
    category: "specialty",
    sealNote: "teflon",
  },
  {
    id: "chlorotrifluoromethane-f13",
    formula: "CClF₃",
    factor: 0.43,
    names: { en: "Chlorotrifluoromethane (f13)" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "cis-2-butene",
    formula: "C₄H₈",
    factor: 0.32,
    names: { en: "CIS-2-Butene" },
    category: "common",
  },
  {
    id: "cyanogen",
    formula: "(CN)₂",
    factor: 0.498,
    names: { en: "Cyanogen" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "cyanogen-chloride",
    formula: "ClCN",
    factor: 0.618,
    names: { en: "Cyanogen Chloride" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "cyclobutane",
    formula: "C₄H₈",
    factor: 0.387,
    names: { en: "Cyclobutane" },
    category: "common",
  },
  {
    id: "cyclopropane",
    formula: "C₃H₆",
    factor: 0.505,
    names: { en: "Cyclopropane" },
    category: "common",
  },
  {
    id: "deuterium",
    formula: "D₂",
    factor: 0.995,
    names: { en: "Deuterium" },
    category: "common",
  },
  {
    id: "diabromodifluoromethane-f12b2",
    formula: "CBr₂F₂",
    factor: 0.363,
    names: { en: "Diabromodifluoromethane (f12B2)" },
    category: "common",
  },
  {
    id: "diborane",
    formula: "B₂H₆",
    factor: 0.448,
    names: { en: "Diborane" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "dichlorodifluoromethane-f12",
    formula: "CCl₂F₂",
    factor: 0.39,
    names: { en: "Dichlorodifluoromethane (f12)" },
    category: "common",
  },
  {
    id: "dichloroethylene",
    formula: "C₂H₂Cl₂",
    factor: 0.397,
    names: { en: "Dichloroethylene" },
    category: "specialty",
  },
  {
    id: "dichlorofluoromethane-f21",
    formula: "CHCl₂F",
    factor: 0.456,
    names: { en: "Dichlorofluoromethane (f21)" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "dichloromethane",
    formula: "CH₂Cl₂",
    factor: 0.522,
    names: { en: "Dichloromethane" },
    category: "specialty",
  },
  {
    id: "dichlorosilane",
    formula: "SiH₂Cl₂",
    factor: 0.442,
    names: { en: "Dichlorosilane" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "diethylamine",
    formula: "C₄H₁N",
    factor: 0.222,
    names: { en: "Diethylamine" },
    category: "specialty",
  },
  {
    id: "diethylsilane",
    formula: "C₄H₁₂Si",
    factor: 0.183,
    names: { en: "Diethylsilane" },
    category: "specialty",
  },
  {
    id: "difluoromethane-r32",
    formula: "CF₂H₂",
    factor: 0.627,
    names: { en: "Difluoromethane (R32)" },
    category: "specialty",
  },
  {
    id: "dimethylamine",
    formula: "(CH₃)₂NH",
    factor: 0.37,
    names: { en: "Dimethylamine" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "dimethylether",
    formula: "(CH₃)₂O",
    factor: 0.392,
    names: { en: "Dimethylether" },
    category: "common",
  },
  {
    id: "dimethylsulfide",
    formula: "C₂H₆S",
    factor: 0.357,
    names: { en: "Dimethylsulfide" },
    category: "specialty",
  },
  {
    id: "dimethylzinc",
    formula: "C₂H₆Zn",
    factor: 0.234,
    names: { en: "Dimethylzinc" },
    category: "specialty",
  },
  {
    id: "disilane",
    formula: "Si₂H₆",
    factor: 0.332,
    names: { en: "Disilane" },
    category: "specialty",
    sealNote: "teflon",
  },
  {
    id: "ethane",
    formula: "C₂H₆",
    factor: 0.49,
    names: { en: "Ethane" },
    category: "common",
  },
  {
    id: "ethanol",
    formula: "C₂H₆O",
    factor: 0.394,
    names: { en: "Ethanol" },
    category: "specialty",
  },
  {
    id: "ethyl-chloride",
    formula: "C₂H₅Cl",
    factor: 0.408,
    names: { en: "Ethyl chloride" },
    category: "common",
  },
  {
    id: "ethylacetylene",
    formula: "C₄H₆",
    factor: 0.365,
    names: { en: "Ethylacetylene" },
    category: "common",
  },
  {
    id: "ethylene",
    formula: "C₂H₄",
    factor: 0.619,
    names: { en: "Ethylene" },
    category: "common",
  },
  {
    id: "ethylene-oxide",
    formula: "C₂H₄O",
    factor: 0.589,
    names: { en: "Ethylene Oxide" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "fluorine",
    formula: "F₂",
    factor: 0.924,
    names: { en: "Fluorine" },
    category: "specialty",
    sealNote: "metal",
  },
  {
    id: "fluoroform-f23",
    formula: "CHF₃",
    factor: 0.529,
    names: { en: "Fluoroform (f23)" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "germanium-tetrachloride",
    formula: "GeCl₄",
    factor: 0.268,
    names: { en: "Germanium Tetrachloride" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "germanium-tetrafluoride",
    formula: "GeF₄",
    factor: 0.356,
    names: { en: "Germanium Tetrafluoride" },
    category: "specialty",
  },
  {
    id: "germanium-tetrahydride-germane",
    formula: "GeH₄",
    factor: 0.559,
    names: { en: "Germanium Tetrahydride (Germane)" },
    category: "specialty",
  },
  {
    id: "halothane-r123b1",
    formula: "C₂HBrClF₃",
    factor: 0.257,
    names: { en: "Halothane (R123B1)" },
    category: "specialty",
  },
  {
    id: "hexafluoroacetone",
    formula: "C₃F₆O",
    factor: 0.219,
    names: { en: "Hexafluoroacetone" },
    category: "specialty",
  },
  {
    id: "hexafluorobenzine",
    formula: "C₆F₆",
    factor: 0.632,
    names: { en: "Hexafluorobenzine" },
    category: "specialty",
  },
  {
    id: "hexafluorobutadiene",
    formula: "C₄F₆",
    factor: 0.213,
    names: { en: "Hexafluorobutadiene" },
    category: "specialty",
  },
  {
    id: "hexafluoroethane-f116",
    formula: "C₂F₆",
    factor: 0.255,
    names: { en: "Hexafluoroethane (f116)" },
    category: "common",
  },
  {
    id: "hexafluoropropylene-hfp",
    formula: "C₃F₆",
    factor: 0.249,
    names: { en: "Hexafluoropropylene (HFP)" },
    category: "common",
  },
  {
    id: "hexamethyldisilane-hmds",
    formula: "(CH₂)₆Si₂",
    factor: 0.139,
    names: { en: "Hexamethyldisilane (HMDS)" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "hexamethyldisiloxane",
    formula: "C₆H₁₈OSi₂",
    factor: 0.11,
    names: { en: "Hexamethyldisiloxane" },
    category: "specialty",
  },
  {
    id: "hexane",
    formula: "C₆H₁₄",
    factor: 0.204,
    names: { en: "Hexane" },
    category: "common",
  },
  {
    id: "hexylamine",
    formula: "C₆H₁₅N",
    factor: 0.158,
    names: { en: "Hexylamine" },
    category: "specialty",
  },
  {
    id: "hydrogen-bromide",
    formula: "HBr",
    factor: 0.987,
    names: { en: "Hydrogen Bromide" },
    category: "common",
  },
  {
    id: "hydrogen-chloride",
    formula: "HCl",
    factor: 0.983,
    names: { en: "Hydrogen Chloride" },
    category: "common",
  },
  {
    id: "hydrogen-cyanide",
    formula: "HCN",
    factor: 0.744,
    names: { en: "Hydrogen Cyanide" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "hydrogen-fluoride",
    formula: "HF",
    factor: 0.998,
    names: { en: "Hydrogen Fluoride" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "hydrogen-iodide",
    formula: "HI",
    factor: 0.953,
    names: { en: "Hydrogen Iodide" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "hydrogen-selenide",
    formula: "H₂Se",
    factor: 0.837,
    names: { en: "Hydrogen Selenide" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "hydrogen-sulfide",
    formula: "H₂S",
    factor: 0.85,
    names: { en: "Hydrogen Sulfide" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "iodine-pentafluoride",
    formula: "IF₅",
    factor: 0.283,
    names: { en: "Iodine Pentafluoride" },
    category: "specialty",
    sealNote: "teflon",
  },
  {
    id: "isobutane",
    formula: "C₄H₁O",
    factor: 0.26,
    names: { en: "Isobutane" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "isobutene",
    formula: "C₄H₈",
    factor: 0.289,
    names: { en: "Isobutene" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "isopentane",
    formula: "C₅H₁₂",
    factor: 0.211,
    names: { en: "Isopentane" },
    category: "specialty",
  },
  {
    id: "krypton",
    formula: "Kr",
    factor: 1.382,
    names: { en: "Krypton" },
    category: "common",
  },
  {
    id: "methacrolein",
    formula: "C₄H₆O",
    factor: 0.313,
    names: { en: "Methacrolein" },
    category: "specialty",
  },
  {
    id: "methane",
    formula: "CH₄",
    factor: 0.763,
    names: { en: "Methane" },
    category: "common",
  },
  {
    id: "methanol",
    formula: "CH₄O",
    factor: 0.609,
    names: { en: "Methanol" },
    category: "specialty",
  },
  {
    id: "methyl-bromide",
    formula: "CH₃Br",
    factor: 0.646,
    names: { en: "Methyl Bromide" },
    category: "specialty",
  },
  {
    id: "methyl-chloride",
    formula: "CH₃Cl",
    factor: 0.687,
    names: { en: "Methyl Chloride" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "methyl-fluoride",
    formula: "CH₃F",
    factor: 0.761,
    names: { en: "Methyl Fluoride" },
    category: "specialty",
  },
  {
    id: "methyl-mercaptan",
    formula: "CH₄S",
    factor: 0.588,
    names: { en: "Methyl Mercaptan" },
    category: "specialty",
  },
  {
    id: "methyl-silane",
    formula: "CH₆Si",
    factor: 0.393,
    names: { en: "Methyl Silane" },
    category: "specialty",
  },
  {
    id: "methyl-trichlorosilane-mts",
    formula: "CH₃Cl₃Si",
    factor: 0.267,
    names: { en: "Methyl Trichlorosilane (MTS)" },
    category: "specialty",
  },
  {
    id: "methyl-vinyl-ether",
    formula: "C₃H₆O",
    factor: 0.337,
    names: { en: "Methyl Vinyl Ether" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "methylacetylene",
    formula: "C₃H₄",
    factor: 0.473,
    names: { en: "Methylacetylene" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "monoethyanolamine",
    formula: "C₂H₇NO",
    factor: 0.305,
    names: { en: "Monoethyanolamine" },
    category: "specialty",
  },
  {
    id: "monoethylamine-ch3ch2nh2",
    formula: "C₂H₇",
    factor: 0.395,
    names: { en: "Monoethylamine (CH3CH2NH2)" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "monomethylamine",
    formula: "CH₃NH₂",
    factor: 0.565,
    names: { en: "Monomethylamine" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "neon",
    formula: "Ne",
    factor: 1.398,
    names: { en: "Neon" },
    category: "common",
  },
  {
    id: "nickel-carbonyl",
    formula: "Ni(CO)₄",
    factor: 0.212,
    names: { en: "Nickel Carbonyl" },
    category: "specialty",
  },
  {
    id: "nitric-acid",
    formula: "HNO₃",
    factor: 0.491,
    names: { en: "Nitric Acid" },
    category: "specialty",
  },
  {
    id: "nitric-oxide",
    formula: "NO",
    factor: 0.995,
    names: { en: "Nitric Oxide" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "nitrogen-dioxide",
    formula: "NO₂",
    factor: 0.758,
    names: { en: "Nitrogen Dioxide" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "nitrogen-trifluoride",
    formula: "NF₃",
    factor: 0.501,
    names: { en: "Nitrogen Trifluoride" },
    category: "specialty",
    sealNote: "teflon",
  },
  {
    id: "nitrogen-trioxide",
    formula: "N₂O₃",
    factor: 0.443,
    names: { en: "Nitrogen Trioxide" },
    category: "specialty",
  },
  {
    id: "nitrosyl-chloride",
    formula: "NOCl",
    factor: 0.664,
    names: { en: "Nitrosyl Chloride" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "nitrous-oxide",
    formula: "N₂O",
    factor: 0.752,
    names: { en: "Nitrous Oxide" },
    category: "common",
  },
  {
    id: "octofluorocyclobutane",
    formula: "C₄F₈",
    factor: 0.169,
    names: { en: "Octofluorocyclobutane" },
    category: "specialty",
  },
  {
    id: "octofluorotetrahydrofuran",
    formula: "C₄F₈O",
    factor: 0.165,
    names: { en: "Octofluorotetrahydrofuran" },
    category: "specialty",
  },
  {
    id: "oxygen-difluoride",
    formula: "OF₂",
    factor: 0.672,
    names: { en: "Oxygen Difluoride" },
    category: "specialty",
  },
  {
    id: "ozone",
    formula: "O₃",
    factor: 0.738,
    names: { en: "Ozone" },
    category: "common",
  },
  {
    id: "pentafluoroethane",
    formula: "C₂HF₅",
    factor: 0.287,
    names: { en: "Pentafluoroethane" },
    category: "specialty",
  },
  {
    id: "pentane-n-pentane",
    formula: "C₅H₁₂",
    factor: 0.212,
    names: { en: "Pentane (n-Pentane)" },
    category: "specialty",
  },
  {
    id: "perchlory-fluoride",
    formula: "ClO₃F",
    factor: 0.448,
    names: { en: "Perchlory Fluoride" },
    category: "specialty",
  },
  {
    id: "perfluoro-2-butene",
    formula: "C₄F₈",
    factor: 0.268,
    names: { en: "Perfluoro-2-Butene" },
    category: "specialty",
  },
  {
    id: "perfluorobutane",
    formula: "C₄F₁₀",
    factor: 0.738,
    names: { en: "Perfluorobutane" },
    category: "specialty",
  },
  {
    id: "perfluoromethyl-vinylether-pmve",
    formula: "PMVE",
    factor: 0.296,
    names: { en: "Perfluoromethyl-Vinylether (PMVE)" },
    category: "specialty",
  },
  {
    id: "perfluoropropane",
    formula: "C₃F₈",
    factor: 0.179,
    names: { en: "Perfluoropropane" },
    category: "specialty",
  },
  {
    id: "phosgene",
    formula: "COCl₂",
    factor: 0.504,
    names: { en: "Phosgene" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "phosphine",
    formula: "PH₃",
    factor: 0.783,
    names: { en: "Phosphine" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "phosphorous-oxychloride",
    formula: "POCl₃",
    factor: 0.327,
    names: { en: "Phosphorous Oxychloride" },
    category: "specialty",
  },
  {
    id: "phosphorous-pentafluoride",
    formula: "PF₅",
    factor: 0.346,
    names: { en: "Phosphorous Pentafluoride" },
    category: "specialty",
  },
  {
    id: "phosphorous-trifluoride",
    formula: "PF₃",
    factor: 0.495,
    names: { en: "Phosphorous Trifluoride" },
    category: "specialty",
  },
  {
    id: "propadiene",
    formula: "C₃H₄",
    factor: 0.439,
    names: { en: "Propadiene" },
    category: "specialty",
  },
  {
    id: "propane-same-as-ch3ch2ch3",
    formula: "C₃H₈",
    factor: 0.343,
    names: { en: "Propane (same as CH3CH2CH3)" },
    category: "common",
  },
  {
    id: "propylene-propene",
    formula: "C₃H₆",
    factor: 0.401,
    names: { en: "Propylene (Propene)*" },
    category: "common",
  },
  {
    id: "rhenium-hexafluoride",
    formula: "ReF₆",
    factor: 0.23,
    names: { en: "Rhenium Hexafluoride" },
    category: "specialty",
  },
  {
    id: "silane",
    formula: "SiH₄",
    factor: 0.625,
    names: { en: "Silane" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "silicon-tetrachloride",
    formula: "SiCl₄",
    factor: 0.31,
    names: { en: "Silicon Tetrachloride" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "silicon-tetrafluoride",
    formula: "SiF₄",
    factor: 0.395,
    names: { en: "Silicon Tetrafluoride" },
    category: "specialty",
    sealNote: "teflon",
  },
  {
    id: "sulfur-dioxide",
    formula: "SO₂",
    factor: 0.728,
    names: { en: "Sulfur Dioxide" },
    category: "common",
  },
  {
    id: "sulfur-hexafluoride",
    formula: "SF₆",
    factor: 0.27,
    names: { en: "Sulfur Hexafluoride" },
    category: "common",
  },
  {
    id: "sulfur-tetrafluoride",
    formula: "SF₄",
    factor: 0.353,
    names: { en: "Sulfur Tetrafluoride" },
    category: "specialty",
  },
  {
    id: "sulfur-trioxide",
    formula: "SO₃",
    factor: 0.535,
    names: { en: "Sulfur Trioxide" },
    category: "specialty",
  },
  {
    id: "sulfuryl-fluoride",
    formula: "SO₂F₂",
    factor: 0.423,
    names: { en: "Sulfuryl Fluoride" },
    category: "specialty",
  },
  {
    id: "tetrachloromethane",
    formula: "CCl₄",
    factor: 0.344,
    names: { en: "Tetrachloromethane" },
    category: "specialty",
  },
  {
    id: "tetraethylsilane",
    formula: "C₈H₂₀Si",
    factor: 0.111,
    names: { en: "Tetraethylsilane" },
    category: "specialty",
  },
  {
    id: "tetrafluoroethylene-tfe",
    formula: "C₂F₄",
    factor: 0.361,
    names: { en: "Tetrafluoroethylene (TFE)" },
    category: "common",
  },
  {
    id: "tetrafluorohydrazine",
    formula: "N₂F₄",
    factor: 0.367,
    names: { en: "Tetrafluorohydrazine" },
    category: "specialty",
  },
  {
    id: "tetramethylsilane",
    formula: "C₄H₁₂Si",
    factor: 0.183,
    names: { en: "Tetramethylsilane" },
    category: "specialty",
  },
  {
    id: "titanium-tetrachloride",
    formula: "TiCl₄",
    factor: 0.296,
    names: { en: "Titanium Tetrachloride" },
    category: "specialty",
  },
  {
    id: "toluene-c6h5",
    formula: "CH₃",
    factor: 0.234,
    names: { en: "Toluene (C6H5)" },
    category: "specialty",
  },
  {
    id: "trans-2-butene",
    formula: "C₄H₈",
    factor: 0.291,
    names: { en: "Trans-2-Butene" },
    category: "specialty",
  },
  {
    id: "trichlorofluoromethane-f11",
    formula: "CCl₃F",
    factor: 0.374,
    names: { en: "Trichlorofluoromethane (f11)" },
    category: "specialty",
    sealNote: "teflon",
  },
  {
    id: "trichlorosilane",
    formula: "SiHCl₃",
    factor: 0.329,
    names: { en: "Trichlorosilane" },
    category: "common",
  },
  {
    id: "trifluoroethane",
    formula: "C₂F₃F₃",
    factor: 0.333,
    names: { en: "Trifluoroethane" },
    category: "specialty",
  },
  {
    id: "trifluoropropene",
    formula: "C₃H₃F₃",
    factor: 0.286,
    names: { en: "Trifluoropropene" },
    category: "specialty",
  },
  {
    id: "trimethyl-aluminum",
    formula: "C₃H₉Al",
    factor: 0.259,
    names: { en: "Trimethyl Aluminum" },
    category: "specialty",
  },
  {
    id: "trimethylamine",
    formula: "(CH₃)₃N",
    factor: 0.316,
    names: { en: "Trimethylamine" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "trimethylgallium",
    formula: "C₃H₉Ga",
    factor: 0.237,
    names: { en: "Trimethylgallium" },
    category: "specialty",
  },
  {
    id: "trimethyloxyborane-tmb",
    formula: "B(OCH₃)₃",
    factor: 0.3,
    names: { en: "Trimethyloxyborane (TMB)" },
    category: "specialty",
  },
  {
    id: "trimethylsilane",
    formula: "C₃H₁₀Si",
    factor: 0.235,
    names: { en: "Trimethylsilane" },
    category: "specialty",
  },
  {
    id: "tungsten-hexafluoride",
    formula: "WF₆",
    factor: 0.227,
    names: { en: "Tungsten Hexafluoride" },
    category: "specialty",
    sealNote: "teflon",
  },
  {
    id: "uranium-hexafluoride",
    formula: "UF₆",
    factor: 0.22,
    names: { en: "Uranium Hexafluoride" },
    category: "specialty",
    sealNote: "teflon",
  },
  {
    id: "vinyl-bromide",
    formula: "C₂H₃Br",
    factor: 0.524,
    names: { en: "Vinyl Bromide" },
    category: "specialty",
  },
  {
    id: "vinyl-chloride",
    formula: "C₂H₃Cl",
    factor: 0.542,
    names: { en: "Vinyl Chloride" },
    category: "common",
  },
  {
    id: "vinyl-fluoride",
    formula: "C₂H₃F",
    factor: 0.576,
    names: { en: "Vinyl Fluoride" },
    category: "specialty",
    sealNote: "kalrez",
  },
  {
    id: "water-vapor",
    formula: "H₂O",
    factor: 0.861,
    names: { en: "Water Vapor" },
    category: "specialty",
  },
  {
    id: "xennon",
    formula: "Xe",
    factor: 1.383,
    names: { en: "Xennon" },
    category: "common",
  },
];

/** Reference gas: N₂, factor 1.000. */
export const REFERENCE_GAS_ID = "nitrogen";

/** Lookup by id. Returns undefined if not found. */
export function getGasFactor(id: string): GasFactor | undefined {
  return GAS_FACTORS.find((g) => g.id === id);
}
